# Generated by Django 2.0.5 on 2018-05-04 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo_Pequeño',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=120, null=True)),
            ],
            options={
                'verbose_name': 'Grupo pequeño',
                'verbose_name_plural': 'Grupos pequeños',
            },
        ),
        migrations.CreateModel(
            name='Iglesia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=120, null=True)),
            ],
            options={
                'verbose_name': 'Iglesia',
                'verbose_name_plural': 'Iglesias',
            },
        ),
        migrations.AddField(
            model_name='grupo_pequeño',
            name='iglesia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iglesia.Iglesia'),
        ),
    ]
