# Generated by Django 2.0.5 on 2018-05-04 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iglesia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo_Pequeño',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=120, null=True)),
            ],
            options={
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupos',
            },
        ),
    ]
