# Generated by Django 2.0.5 on 2018-05-07 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iglesia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo_pequeño',
            name='numero_de_miembos',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
