# Generated by Django 2.0.5 on 2018-05-04 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p_iglesia', '0002_grupo_pequeño'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grupo_pequeño',
            options={'verbose_name': 'Grupo pequeño', 'verbose_name_plural': 'Grupos pequeños'},
        ),
    ]
