# Generated by Django 2.0.5 on 2018-05-04 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pastor',
            options={'verbose_name': 'Pastor', 'verbose_name_plural': 'Pastores'},
        ),
    ]
